Repository uchicago-capp-30320/apt-plus, pull requests merged in 2025-05, with the labels that each got.

#62 Update docs
  docs/endpoints.md
  docs/model/erd.png
Labels: Documentation

#70 fix(search): reconnect search button on apt filter page
  templates/home.html
Labels: S, Frontend

#89 Update footer and navbar
  static/css/bulma.css
  static/css/home.css
  templates/footer.html
  templates/home.html
  templates/map.html
  templates/navbar.html
Labels: S, Frontend

#104 Add address saving into JS for save/delete endpoints
  static/js/address_submission.js
Labels: S, Frontend

#103 19 add filters
  static/js/address_submission.js
  templates/address_search/filters.html
  templates/home.html
  templates/map.html
Labels: Frontend

#109 Add fetch calls
  apt_app/views/fetch_inspections.py
  static/css/home.css
  static/js/address_submission.js
  static/js/map_state.js
  templates/home.html
  uv.lock
Labels: Frontend

#119 19 clean map functions
  templates/map.html
Labels: Frontend, GIS

#125 feat: connect fetch endpoints
  static/js/address_submission.js
  static/js/map_modifications.js
  static/js/map_state.js
  templates/address_search/filters.html
  templates/home.html
  templates/map.html
Labels: Frontend, Critical

#124 Update front panel aesthetics
  static/css/home.css
  templates/address_search/filters.html
  templates/home.html
Labels: S, Frontend

#127 feat(frontend): refactor property save/delete interaction with backen…
  apt_app/migrations/0015_rename_property_savedproperty_property_obj_and_more.py
  apt_app/models.py
  apt_app/views/delete_property.py
  apt_app/views/save_property.py
  static/css/htmx-transition.css
  static/js/address_submission.js
  templates/base.html
  templates/home.html
  templates/snippets/save_property_login_required.html
Labels: M, Frontend, High priority

#136 Add comparison page
  apt_app/models.py
  apt_app/views/saved_properties.py
  apt_app/views/views.py
  config/urls.py
  templates/footer.html
  templates/navbar.html
  templates/saved_properties.html
  templates/snippets/saved_properties_delete.html
Labels: M, Frontend, Backend, High priority

#143 Update readme
  COLLABORATION.md
  README.md
  docs/data_privacy.md
Labels: Documentation

#146 fix: correct typo in urls.py causing incorrect endpoint triggering
  config/urls.py
Labels: Backend, Critical

#159 Standardize marker colors, map login screens and UChicago marker
  static/js/address_submission.js
  static/js/init_map.js
  static/js/map_modifications.js
  templates/base.html
  templates/home.html
Labels: S, Frontend
